namespace Sender.Api;

public interface IUploadRepository
{
    /// <summary>
    /// Uploads gzip-compressed content generated by the supplied stream writer.
    /// </summary>
    /// <param name="command">Validated upload command containing the receiver endpoint.</param>
    /// <param name="writePayloadAsync">Callback that writes uncompressed payload bytes into the provided stream.</param>
    /// <param name="cancellationToken">Token used to cancel the upload.</param>
    /// <returns>Upload response details.</returns>
    Task<RepositoryUploadResult> UploadGzipAsync(
        StartUploadCommand command,
        Func<Stream, CancellationToken, Task> writePayloadAsync,
        CancellationToken cancellationToken);
}
